# mir/mir_robot_editor/pyproject.toml
[project]
name = "mir_robot_editor"
version = "0.1.0"
dependencies = ["mir_robot", "mir_devices", "mir_utils"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["mir_robot_editor"]

[tool.setuptools.package-dir]
"mir_robot_editor" = "."